import { readdirSync } from "node:fs";
import { join } from "node:path";

export const SRC_DIR: string = join(import.meta.dirname, "..", "src");
export const PROBLEMS_DIR: string = join(SRC_DIR, "problems");
export const STRUCTURES_DIR: string = join(SRC_DIR, "structures");

/** A LeetCode URL slug, e.g. `two-sum` or `3sum-closest`. */
export const SLUG: RegExp = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

/** A problem folder: the zero-padded problem number followed by its slug, e.g. `0001-two-sum`. */
export const PROBLEM_FOLDER: RegExp = /^(\d{4})-([a-z0-9]+(?:-[a-z0-9]+)*)$/;

export interface Problem {
	folder: string;
	number: number;
	slug: string;
	exportName: string;
}

const DIGIT_WORDS = [
	"zero",
	"one",
	"two",
	"three",
	"four",
	"five",
	"six",
	"seven",
	"eight",
	"nine",
];

const ROMAN_NUMERAL = /^(?:ii|iii|iv|vi|vii|viii|ix)$/;

const capitalize = (word: string): string =>
	ROMAN_NUMERAL.test(word)
		? word.toUpperCase()
		: word.charAt(0).toUpperCase() + word.slice(1);

/**
 * Derives a solution's export name from its LeetCode slug. Slugs are unique,
 * so the names never collide.
 *
 * Leading digits are spelled out so the name is a valid identifier, and roman
 * numeral suffixes are upper-cased.
 *
 * @example
 * exportName("two-sum"); // "twoSum"
 * exportName("3sum-closest"); // "threeSumClosest"
 * exportName("two-sum-ii-input-array-is-sorted"); // "twoSumIIInputArrayIsSorted"
 */
export const exportName = (slug: string): string => {
	const leadingDigits = /^\d*/.exec(slug)?.[0] ?? "";
	const words = [
		...Array.from(leadingDigits, (digit) => DIGIT_WORDS[Number(digit)] ?? ""),
		...slug.slice(leadingDigits.length).split("-"),
	].filter((word) => word !== "");

	return words.map((word, i) => (i === 0 ? word : capitalize(word))).join("");
};

/** Converts a slug into a starting point for the problem's title, e.g. `Two Sum`. */
export const titleFromSlug = (slug: string): string =>
	slug.split("-").map(capitalize).join(" ");

export const problemFolder = (number: number, slug: string): string =>
	`${String(number).padStart(4, "0")}-${slug}`;

/** Lists every problem in `src/problems`, ordered by problem number. */
export const listProblems = (): Problem[] =>
	readdirSync(PROBLEMS_DIR, { withFileTypes: true })
		.filter((entry) => entry.isDirectory())
		.map(({ name: folder }) => {
			const match = PROBLEM_FOLDER.exec(folder);
			if (!match?.[1] || !match[2]) {
				throw new Error(
					`src/problems/${folder} must be named <4-digit number>-<leetcode-slug>, e.g. 0001-two-sum`,
				);
			}
			return {
				folder,
				number: Number(match[1]),
				slug: match[2],
				exportName: exportName(match[2]),
			};
		})
		.toSorted((a, b) => a.number - b.number);

/** Lists the modules in `src/structures`, without their `.ts` extension. */
export const listStructures = (): string[] =>
	readdirSync(STRUCTURES_DIR)
		.filter((file) => file.endsWith(".ts") && !file.endsWith(".test.ts"))
		.map((file) => file.slice(0, -".ts".length))
		.toSorted();

/**
 * Renders `src/index.ts`, the package's single entry point. The exports are in
 * the order Biome's import sorting expects.
 */
export const renderIndex = (): string =>
	[
		"// Generated by `bun run generate`. Do not edit by hand.",
		"",
		...listProblems().map(
			({ folder, exportName }) =>
				`export { ${exportName} } from "./problems/${folder}";`,
		),
		...listStructures().map((name) => `export * from "./structures/${name}";`),
		"",
	].join("\n");
