import {
	mkdirSync,
	readdirSync,
	readFileSync,
	rmSync,
	writeFileSync,
} from "node:fs";
import { join } from "node:path";

export const ROOT_DIR: string = join(import.meta.dirname, "..");
export const SRC_DIR: string = join(ROOT_DIR, "src");
export const PROBLEMS_DIR: string = join(SRC_DIR, "problems");
export const STRUCTURES_DIR: string = join(SRC_DIR, "structures");

// Generated and synced files, relative to the repo root.
export const INDEX_FILE = "src/index.ts";
export const CATALOGUE_FILE = "data/leetcode-problems.json";
export const PROBLEM_LIST_FILE = "PROBLEMS.md";
export const PROBLEM_PAGES_DIR = "docs/problems";

/** A LeetCode URL slug, e.g. `two-sum` or `3sum-closest`. */
export const SLUG: RegExp = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

/** A problem folder: the zero-padded problem number followed by its slug, e.g. `0001-two-sum`. */
export const PROBLEM_FOLDER: RegExp = /^(\d{4})-([a-z0-9]+(?:-[a-z0-9]+)*)$/;

export interface Problem {
	folder: string;
	number: number;
	slug: string;
	exportName: string;
}

export type Difficulty = "Easy" | "Medium" | "Hard";

/** A problem as listed by LeetCode. */
export interface LeetCodeProblem {
	number: number;
	title: string;
	slug: string;
	difficulty: Difficulty;
	premium: boolean;
}

/** Every LeetCode problem, as downloaded by `bun run sync`. */
export interface Catalogue {
	syncedAt: string;
	problems: LeetCodeProblem[];
}

const DIGIT_WORDS = [
	"zero",
	"one",
	"two",
	"three",
	"four",
	"five",
	"six",
	"seven",
	"eight",
	"nine",
];

const ROMAN_NUMERAL = /^(?:ii|iii|iv|vi|vii|viii|ix)$/;

const capitalize = (word: string): string =>
	ROMAN_NUMERAL.test(word)
		? word.toUpperCase()
		: word.charAt(0).toUpperCase() + word.slice(1);

/**
 * Derives a solution's export name from its LeetCode slug. Slugs are unique,
 * so the names never collide.
 *
 * Leading digits are spelled out so the name is a valid identifier, and roman
 * numeral suffixes are upper-cased.
 *
 * @example
 * exportName("two-sum"); // "twoSum"
 * exportName("3sum-closest"); // "threeSumClosest"
 * exportName("two-sum-ii-input-array-is-sorted"); // "twoSumIIInputArrayIsSorted"
 */
export const exportName = (slug: string): string => {
	const leadingDigits = /^\d*/.exec(slug)?.[0] ?? "";
	const words = [
		...Array.from(leadingDigits, (digit) => DIGIT_WORDS[Number(digit)] ?? ""),
		...slug.slice(leadingDigits.length).split("-"),
	].filter((word) => word !== "");

	return words.map((word, i) => (i === 0 ? word : capitalize(word))).join("");
};

export const problemFolder = (number: number, slug: string): string =>
	`${String(number).padStart(4, "0")}-${slug}`;

/** Lists every problem in `src/problems`, ordered by problem number. */
export const listProblems = (): Problem[] =>
	readdirSync(PROBLEMS_DIR, { withFileTypes: true })
		.filter((entry) => entry.isDirectory())
		.map(({ name: folder }) => {
			const match = PROBLEM_FOLDER.exec(folder);
			if (!match?.[1] || !match[2]) {
				throw new Error(
					`src/problems/${folder} must be named <4-digit number>-<leetcode-slug>, e.g. 0001-two-sum`,
				);
			}
			return {
				folder,
				number: Number(match[1]),
				slug: match[2],
				exportName: exportName(match[2]),
			};
		})
		.toSorted((a, b) => a.number - b.number);

/** Lists the modules in `src/structures`, without their `.ts` extension. */
export const listStructures = (): string[] =>
	readdirSync(STRUCTURES_DIR)
		.filter((file) => file.endsWith(".ts") && !file.endsWith(".test.ts"))
		.map((file) => file.slice(0, -".ts".length))
		.toSorted();

/**
 * Renders `src/index.ts`, the package's single entry point. The exports are in
 * the order Biome's import sorting expects.
 */
export const renderIndex = (): string =>
	[
		"// Generated by `bun run generate`. Do not edit by hand.",
		"",
		...listProblems().map(
			({ folder, exportName }) =>
				`export { ${exportName} } from "./problems/${folder}";`,
		),
		...listStructures().map((name) => `export * from "./structures/${name}";`),
		"",
	].join("\n");

export const readCatalogue = (): Catalogue =>
	JSON.parse(readFileSync(join(ROOT_DIR, CATALOGUE_FILE), "utf8")) as Catalogue;

export const problemUrl = (slug: string): string =>
	`https://leetcode.com/problems/${slug}/`;

const escapeMarkdown = (text: string): string =>
	text.replace(/[\\`*_[\]<>|]/g, "\\$&");

const percent = (part: number, whole: number): string =>
	`${whole === 0 ? "0.0" : ((part / whole) * 100).toFixed(1)}%`;

/**
 * Problems per page of the problem list. GitHub stops rendering Markdown files
 * over 512 KB, and a full page of 1000 implemented problems is about 170 KB.
 */
const PAGE_SIZE = 1000;

const GENERATED_NOTICE =
	"Generated by `bun run generate`. Do not edit by hand.";

const pageFile = (first: number): string =>
	`${PROBLEM_PAGES_DIR}/${String(first).padStart(4, "0")}-${first + PAGE_SIZE - 1}.md`;

/**
 * Renders `PROBLEMS.md` and its pages in `docs/problems`, which list every
 * LeetCode problem and whether it's implemented. Keyed by path relative to the
 * repo root.
 */
export const renderProblemList = (): Map<string, string> => {
	const { syncedAt, problems } = readCatalogue();
	const implemented = new Map(
		listProblems().map((problem) => [problem.number, problem]),
	);
	const countDone = (list: LeetCodeProblem[]): number =>
		list.filter(({ number }) => implemented.has(number)).length;
	const progress = (label: string, list: LeetCodeProblem[]): string => {
		const done = countDone(list);
		return `| ${label} | ${done} | ${list.length} | ${percent(done, list.length)} |`;
	};

	const pages = new Map<number, LeetCodeProblem[]>();
	for (const problem of problems) {
		const first = Math.floor((problem.number - 1) / PAGE_SIZE) * PAGE_SIZE + 1;
		pages.set(first, [...(pages.get(first) ?? []), problem]);
	}

	const files = new Map<string, string>();

	files.set(
		PROBLEM_LIST_FILE,
		[
			"# Problems",
			"",
			"Every LeetCode problem and whether leetils implements it.",
			"",
			`${GENERATED_NOTICE} Problems come from [${CATALOGUE_FILE}](${CATALOGUE_FILE}), last synced with LeetCode on ${syncedAt} by \`bun run sync\`.`,
			"",
			"## Progress",
			"",
			"| Difficulty | Implemented | Total | Progress |",
			"| --- | ---: | ---: | ---: |",
			...(["Easy", "Medium", "Hard"] as const).map((difficulty) =>
				progress(
					difficulty,
					problems.filter((problem) => problem.difficulty === difficulty),
				),
			),
			progress("**All**", problems),
			"",
			"## Problem list",
			"",
			"| Problems | Implemented | Total | Progress |",
			"| --- | ---: | ---: | ---: |",
			...[...pages].map(([first, list]) =>
				progress(
					`[${first}–${first + PAGE_SIZE - 1}](${pageFile(first)})`,
					list,
				),
			),
			"",
		].join("\n"),
	);

	for (const [first, list] of pages) {
		const rows = list.map(({ number, title, slug, difficulty, premium }) => {
			const solution = implemented.get(number);
			const link = `[${escapeMarkdown(title)}](${problemUrl(slug)})${premium ? " 🔒" : ""}`;
			const status = solution
				? `✅ [\`${solution.exportName}\`](../../src/problems/${solution.folder}/index.ts)`
				: "";
			return `| ${number} | ${link} | ${difficulty} | ${status} |`;
		});

		files.set(
			pageFile(first),
			[
				`# Problems ${first}–${first + PAGE_SIZE - 1}`,
				"",
				`[All problems](../../${PROBLEM_LIST_FILE}). 🔒 marks LeetCode Premium problems. ${GENERATED_NOTICE}`,
				"",
				`**${countDone(list)} of ${list.length} implemented.**`,
				"",
				"| # | Problem | Difficulty | Implemented |",
				"| ---: | --- | --- | --- |",
				...rows,
				"",
			].join("\n"),
		);
	}

	return files;
};

/**
 * Renders every generated file: `src/index.ts` and the problem list. Keyed by
 * path relative to the repo root.
 */
export const renderGeneratedFiles = (): Map<string, string> =>
	new Map([[INDEX_FILE, renderIndex()], ...renderProblemList()]);

/** Writes every generated file, and removes problem list pages that are no longer generated. */
export const writeGeneratedFiles = (): void => {
	const files = renderGeneratedFiles();

	mkdirSync(join(ROOT_DIR, PROBLEM_PAGES_DIR), { recursive: true });
	for (const file of readdirSync(join(ROOT_DIR, PROBLEM_PAGES_DIR))) {
		const path = `${PROBLEM_PAGES_DIR}/${file}`;
		if (!files.has(path)) rmSync(join(ROOT_DIR, path));
	}

	for (const [path, content] of files) {
		writeFileSync(join(ROOT_DIR, path), content);
	}
};
